# ==============================================
# Docker Compose - ClassCheck Development Environment
# Stack: Next.js + TypeScript + MySQL + Prisma
# ==============================================

services:
  # ===================
  # APLICAÇÃO NEXT.JS
  # ===================
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classcheck-app
    
    # Mapeamento de portas: HOST:CONTAINER
    ports:
      - "3000:3000"
    
    # Variáveis de ambiente
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://classcheck_user:classcheck_password@db:5432/classcheck_db?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
    
    # Volumes para hot reload e persistência
    volumes:
      # Montar código fonte (permite hot reload)
      - .:/app
      # Volume anônimo para node_modules (evita conflitos Windows/Linux)
      - /app/node_modules
      # Montar Next.js cache
      - ./.next:/app/.next
    
    # Dependências de outros serviços
    depends_on:
      db:
        condition: service_healthy
    
    # Rede customizada
    networks:
      - classcheck-network
    
    # Política de restart
    restart: unless-stopped
    
    # Comando para aguardar o banco estar pronto
    command: >
      sh -c "
        echo 'Aguardando banco de dados...' &&
        sleep 10 &&
        echo 'Iniciando aplicação Next.js...' &&
        npm run dev
      "

  # ===================
  # BANCO POSTGRESQL
  # ===================
  db:
    image: postgres:16-alpine
    container_name: classcheck-db
    
    # Mapeamento de portas: HOST:CONTAINER
    ports:
      - "5433:5432"
    
    # Variáveis de ambiente do PostgreSQL
    environment:
      POSTGRES_DB: classcheck_db
      POSTGRES_USER: classcheck_user
      POSTGRES_PASSWORD: classcheck_password
      POSTGRES_ROOT_PASSWORD: root_password
    
    # Volume para persistir dados do banco
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Scripts de inicialização (opcional)
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    
    # Rede customizada
    networks:
      - classcheck-network
    
    # Health check para garantir que o banco está pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U classcheck_user -d classcheck_db"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 40s
    
    # Política de restart
    restart: unless-stopped

  # ===================
  # PGADMIN (OPCIONAL)
  # Interface web para gerenciar PostgreSQL - Alternativa ao DBeaver
  # ===================
  # Descomente as linhas abaixo se preferir usar uma interface web
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: classcheck-pgadmin
  #   
  #   ports:
  #     - "8080:80"
  #   
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@classcheck.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   
  #   networks:
  #     - classcheck-network
  #   
  #   restart: unless-stopped

# ===================
# VOLUMES
# ===================
volumes:
  # Volume nomeado para persistir dados do PostgreSQL
  postgres_data:
    driver: local

# ===================
# NETWORKS
# ===================
networks:
  # Rede customizada para isolamento
  classcheck-network:
    driver: bridge

# ==============================================
# COMANDOS ÚTEIS:
# 
# Subir ambiente:
#   docker-compose up --build
# 
# Subir em background:
#   docker-compose up -d --build
# 
# Ver logs:
#   docker-compose logs -f app
#   docker-compose logs -f db
# 
# Executar comandos no container:
#   docker-compose exec app npm run lint
#   docker-compose exec app npx prisma migrate dev
#   docker-compose exec app npx prisma studio
# 
# Parar ambiente:
#   docker-compose down
# 
# Parar e remover volumes:
#   docker-compose down -v
# 
# Rebuild completo:
#   docker-compose down && docker-compose build --no-cache && docker-compose up
# ==============================================
